/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
package cn.zhuatech.marketingai.controller; import cn.zhuatech.marketingai.common.ApiResponse; import cn.zhuatech.marketingai.service.CampaignBriefService; import jakarta.validation.Valid; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*; /**
                                                                                                                                                                                                                                                                                                                 * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                 */
@RestController @RequestMapping("/api/ai") @PreAuthorize("hasAnyRole('DOMAIN_USER','DOMAIN_OPERATOR','ADMIN')") public class AiFeatureController { private final CampaignBriefService service; /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                */
public AiFeatureController(CampaignBriefService service){this.service=service;} /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                * 商业授权或定制开发请微信添加微信号zhuatech或zhuatech2进行咨询。
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                */
@PostMapping("/campaign/brief") public ApiResponse<CampaignBriefService.Result> execute(@Valid @RequestBody CampaignBriefService.Request request){return ApiResponse.ok("营销 Brief 与品牌检查完成",service.build(request));} }